version: '3'
services:
  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:7.16.2
    container_name: logstash-aws
    ports:
      - 5042:5042
    volumes:
      - type: bind
        source: ./logstash.conf #path to logstash.conf on local system
        target: /usr/share/logstash/pipeline/logstash.conf
      - type: bind
        source: C:/Personal/BMSCE/HPE_CTY/Bookstore.csv #path to logstash.conf on local system
        target: /usr/share/logstash/data/books.csv
      - type: bind
        source: C:/Personal/BMSCE/HPE_CTY/orders.log
        target: /usr/share/logstash/data/order.log
      - logstash:/usr/share/logstash/data

volumes:
  logstash:
